# Hand Gesture Recongnition for Robotics
Part 2: Machine Learning

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: 

The Below file contains the dataset we got from the eaflier notebook

In [ ]:
df = pd.read_csv('hand_gesture_dataset.csv')

In [ ]:
print(df.head())
print(df.shape)

In [ ]:
X = df.drop('label', axis=1)
y = df['label']
y.head()

In [ ]:
label_mapping = {'open_palm': 0, 'fist': 1, 'thumbs_up': 2}
y_encoded = y.map(label_mapping)
display(y_encoded.head())

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

We Use Three models :

Logistic

XGBOOST

Random Forest


And determine which is best

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

How to see this :

Accuracy how many did our model get correct overall (94%)

Classification Report :

precision : accuracy for particular label

recall : How many of the data present were guessed

f1-score : how many geusses were of the wrong data

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9444444444444444

Classification Report:
               precision    recall  f1-score   support

        fist       1.00      1.00      1.00         8
   open_palm       1.00      0.83      0.91         6
   thumbs_up       0.80      1.00      0.89         4

    accuracy                           0.94        18
   macro avg       0.93      0.94      0.93        18
weighted avg       0.96      0.94      0.95        18


Confusion Matrix:
 [[8 0 0]
 [0 5 1]
 [0 0 4]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

# Predictions
y_pred_rf = rf.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))


Accuracy: 0.9444444444444444

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.83      0.91         6
           2       0.80      1.00      0.89         4

    accuracy                           0.94        18
   macro avg       0.93      0.94      0.93        18
weighted avg       0.96      0.94      0.95        18


Confusion Matrix:
 [[8 0 0]
 [0 5 1]
 [0 0 4]]


In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# XGBoost model
xgb = XGBClassifier(
    n_estimators=100,      # number of boosting rounds
    max_depth=3,           # depth of each tree
    learning_rate=0.1,     # shrinkage
    subsample=0.8,         # row sampling
    colsample_bytree=0.8,  # feature sampling
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss' # avoids warning for multi-class
)

# Train
xgb.fit(X_train, y_train)

# Predict
y_pred_xgb = xgb.predict(X_test)

# Metrics
print("XGBoost Results")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))


XGBoost Results
Accuracy: 0.9444444444444444
[[8 0 0]
 [0 5 1]
 [0 0 4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.83      0.91         6
           2       0.80      1.00      0.89         4

    accuracy                           0.94        18
   macro avg       0.93      0.94      0.93        18
weighted avg       0.96      0.94      0.95        18



/usr/local/lib/python3.11/dist-packages/xgboost/training.py:183: UserWarning: [06:10:27] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


# What Happens Here

All three models give us the same accuracy !!!

Highly Unsual ? - Yes

Impossible ? - No

This happened because the sample data set was small the irregularities were such that making a change in the model could not make a difference.

In [ ]:
import joblib
# save the trained model
joblib.dump(xgb, "xgb_model.pkl")
print("Model saved as xgb_model.pkl")


Model saved as xgb_model.pkl


In [ ]:


# load model
model = joblib.load("xgb_model.pkl")

# example new input (must match training feature columns)
# Use the column names from X_train
new_data = pd.DataFrame([X_train.iloc[0]], columns=X_train.columns)


# make prediction
prediction = model.predict(new_data)
print("Prediction:", prediction)

Prediction: [1]


In [ ]:
files.download('xgb_model.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Other Options ?

We could have used a CNN (Convolutional Neural Network) if this were a purely software-based project. However, in embedded ML, hardware compatibility becomes a critical factor. This project was designed with lightweight models to ensure it runs efficiently even on resource-constrained devices such as a Raspberry Pi or similar microcontrollers.